# Generated by Django 4.1.5 on 2023-01-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seccode_list',
            fields=[
                ('seccode', models.IntegerField(max_length=5, primary_key=True, serialize=False, verbose_name='銘柄コード')),
                ('company_name', models.CharField(max_length=50, verbose_name='銘柄名')),
                ('settlement_month', models.CharField(max_length=2, verbose_name='決済月')),
                ('dividends_zenki', models.IntegerField(max_length=10, verbose_name='配当金（前期）')),
                ('dividends_yosou', models.IntegerField(max_length=10, verbose_name='配当金（予想）')),
                ('shares', models.IntegerField(max_length=20, verbose_name='発行済株式数')),
            ],
            options={
                'db_table': 'seccode_list',
            },
        ),
    ]
