# Generated by Django 4.1.5 on 2023-01-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('seccode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='screening_list',
            fields=[
                ('seccode', models.IntegerField(primary_key=True, serialize=False, verbose_name='銘柄コード')),
                ('company_name', models.CharField(max_length=50, verbose_name='銘柄名')),
                ('industry', models.CharField(max_length=50, verbose_name='業種')),
                ('priority_market', models.CharField(max_length=50, verbose_name='優先市場')),
                ('settlement_month', models.CharField(max_length=2, verbose_name='決済月')),
                ('accounting_standards', models.CharField(max_length=50, verbose_name='会計基準')),
                ('market_capitalization', models.IntegerField(verbose_name='時価総額')),
                ('ev_ebitda', models.FloatField(verbose_name='EV/EBITDA')),
                ('dividends_zenki', models.IntegerField(verbose_name='配当金（前期）')),
                ('dividends_yosou', models.IntegerField(verbose_name='配当金（予想）')),
                ('dividend_yield', models.FloatField(verbose_name='配当利回り')),
                ('own_capital_ratio', models.FloatField(verbose_name='自己資本比率')),
                ('operating_cf', models.IntegerField(verbose_name='営業キャッシュフロー')),
                ('shares', models.IntegerField(verbose_name='発行済株式数')),
            ],
            options={
                'db_table': 'screening_list',
            },
        ),
        migrations.AlterField(
            model_name='seccode_list',
            name='dividends_yosou',
            field=models.IntegerField(verbose_name='配当金（予想）'),
        ),
        migrations.AlterField(
            model_name='seccode_list',
            name='dividends_zenki',
            field=models.IntegerField(verbose_name='配当金（前期）'),
        ),
        migrations.AlterField(
            model_name='seccode_list',
            name='seccode',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='銘柄コード'),
        ),
        migrations.AlterField(
            model_name='seccode_list',
            name='shares',
            field=models.IntegerField(verbose_name='発行済株式数'),
        ),
    ]
